apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskmanager.fullname" . }}-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password | default "CHANGE_ME" }}@{{ include "taskmanager.fullname" . }}-postgres:5432/{{ .Values.postgres.database }}"
  REDIS_URL: "redis://{{ include "taskmanager.fullname" . }}-redis:6379/0"
  SECRET_KEY: {{ .Values.backend.secretKey | default "CHANGE_ME_IN_CI" | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | default "CHANGE_ME" | quote }}
